import jsQR from 'jsqr';
import { type Asset } from '../types';

/**
 * Extracts asset tag, serial number, or barcode payload from raw QR code text or formatted label payload.
 */
export function parseQrPayloadToAssetTag(raw: string): string {
  if (!raw) return '';
  const trimmed = raw.trim();

  // 1. Check if prefix exists
  if (trimmed.startsWith('HITOMS-ASSET:')) {
    return trimmed.replace('HITOMS-ASSET:', '').trim();
  }

  // 2. Check if JSON payload
  try {
    const json = JSON.parse(trimmed);
    if (json && typeof json === 'object') {
      if (json.assetTag) return String(json.assetTag).trim();
      if (json.tag) return String(json.tag).trim();
      if (json.serialNumber) return String(json.serialNumber).trim();
      if (json.id) return String(json.id).trim();
    }
  } catch {
    // Not JSON
  }

  // 3. Check for multiline label payload generated by app
  const lines = trimmed.split('\n');
  for (const line of lines) {
    if (line.includes('ASSET TAG:')) {
      const parts = line.split('ASSET TAG:');
      if (parts[1]) return parts[1].trim();
    }
  }

  for (const line of lines) {
    if (line.includes('SERIAL (S/N):')) {
      const parts = line.split('SERIAL (S/N):');
      if (parts[1]) return parts[1].trim();
    }
  }

  // 4. Regex pattern matching common Asset Tag formats e.g. HIT-AST-000101, AST-HOSP-00104, TAG-001
  const tagRegex = /(HIT-AST-[0-9A-Za-z-]+|AST-[0-9A-Za-z-]+|TAG-[0-9A-Za-z-]+)/i;
  const match = trimmed.match(tagRegex);
  if (match && match[0]) {
    return match[0].trim();
  }

  return trimmed;
}

/**
 * Given a scanned raw QR string and list of assets, finds the matching asset by Tag, Serial, or ID.
 */
export function findAssetFromQrScan(raw: string, assets: Asset[]): Asset | null {
  if (!raw || !assets || assets.length === 0) return null;
  const parsedTag = parseQrPayloadToAssetTag(raw).toLowerCase();
  if (!parsedTag) return null;

  // 1. Exact match on assetTag
  let found = assets.find((a) => a.assetTag.toLowerCase() === parsedTag);
  if (found) return found;

  // 2. Exact match on serialNumber
  found = assets.find((a) => a.serialNumber && a.serialNumber.toLowerCase() === parsedTag);
  if (found) return found;

  // 3. Exact match on ID
  found = assets.find((a) => a.id.toLowerCase() === parsedTag);
  if (found) return found;

  // 4. Partial inclusion match on assetTag or serialNumber
  found = assets.find(
    (a) =>
      a.assetTag.toLowerCase().includes(parsedTag) ||
      (a.serialNumber && a.serialNumber.toLowerCase().includes(parsedTag))
  );

  return found || null;
}

/**
 * Reads image data from an HTML Canvas and decodes QR code using jsQR.
 */
export function decodeQrFromCanvas(
  canvas: HTMLCanvasElement
): { data: string; assetTag: string } | null {
  const ctx = canvas.getContext('2d');
  if (!ctx) return null;

  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const code = jsQR(imageData.data, imageData.width, imageData.height, {
    inversionAttempts: 'dontInvert',
  });

  if (code && code.data) {
    return {
      data: code.data,
      assetTag: parseQrPayloadToAssetTag(code.data),
    };
  }

  return null;
}
